# Generated by Django 4.1.2 on 2022-11-15 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='date_measurement',
            new_name='created_at',
        ),
    ]
