version: '3.9'

services:
  web:
    build: .
    command: gunicorn stocks_products.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/api/staticfiles
    expose:
      - 8000
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=netology_stocks_products
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - static_volume:/usr/src/api/staticfiles
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
